config/routes.rb
Rails.application.routes.draw do
  devise_for :users

   root 'welcome#index'

   resources :records
   resources :movies

end

app/models/movie.rb
class Movie < ActiveRecord::Base
end

app/models/record.rb
class Record < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :current_user

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.create movie_params
    redirect_to root_path
  end

  def edit
    @movie = Movie.find params[:id]
  end

  def update
    @movie = Movie.find params[:id]
    @movie.update_attributes movie_params
    redirect_to root_path
  end

  def show
    @movie = Movie.find params[:id]
  end

   def destroy
    @movie = Movie.find params[:id]
    @movie.delete
    redirect_to root_path
  end

private
  def movie_params
    params.require(:movie).permit(:title, :notes)
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :user_signed_in?

  def index
    @records = Record.all
  end

  def new
    @record = Record.new
  end

  def create
    @record = Record.create record_params
    redirect_to root_path
  end

  def edit
    @record = Record.find params[:id]
  end

  def update
    @record = Record.find params[:id]
    @record.update_attributes record_params
    redirect_to root_path
  end
  
  def show
    @record = Record.find params[:id]
  end

  def destroy
    @record = Record.find params[:id]
    @record.delete
    redirect_to root_path
  end


private
  def record_params
    params.require(:record).permit(:title, :notes)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @records = Record.all
    @movies = Movie.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  
<head>
  <title>MY STUFF</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link href="/assets/styles.css" media="screen" rel="stylesheet" />

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
 
       
</head>
<body>


<%= yield %>

</body>
</html>

app/views/movies/edit.html.erb
<h1>Movies<h1>

<%= form_for @movie do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :notes %>
  <%= f.text_area :notes %>
  <br>
  <%= f.submit %>
<% end %>

app/views/movies/new.html.erb
<h1>Movies<h1>

<%= form_for @movie do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :notes %>
  <%= f.text_area :notes %>
  <br>
  <%= f.submit %>
<% end %>

app/views/movies/show.html.erb
<h1>MOVIES</h1>

<%= @movie.title %>
<br>
<br>
<%= @movie.notes %>
<br>
<%= link_to "HOME", root_path %>

app/views/records/edit.html.erb
<h1>EDIT RECORD</h1>

<%= form_for @record do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :artist %>
  <%= f.text_field :artist %>
  <br>
  <%= f.label :notes %>
  <%= f.text_area :notes %>
  <br>
  <%= f.submit %>
<% end %>

app/views/records/new.html.erb
<h1>NEW RECORD</h1>

<%= form_for @record do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :artist %>
  <%= f.text_field :artist %>
  <br>
  <%= f.label :notes %>
  <%= f.text_area :notes %>
  <br>
  <%= f.submit %>
<% end %>

app/views/records/show.html.erb
<h1>YOUR SELECTION</h1>

<%= @record.title %>
<br>
<%= @record.artist %>
<br>
<%= @record.notes %>
<br>
<%= link_to "MAIN", root_path %>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

    <%= yield %>
    <%= javascript_include_tag "application" %>

<body>
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><a href="#">My Stuff</a></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li class="has-form">
        <div class="row collapse">
          <div class="large-8 small-9 columns">
            <input type="text" placeholder="Find Stuff">
          </div>
          <div class="large-4 small-3 columns">
            <a href="#" class="alert button expand">Search</a>
          </div>
        </div>
      </li>
      <li class="has-dropdown">
        <a href="#">Right Button Dropdown</a>
        <ul class="dropdown">
          <li><a href="#">First link in dropdown</a></li>
          <li class="active"><a href="#">Active link in dropdown</a></li>
        </ul>
      </li>
    </ul>

    
  </section>
</nav>
<h1>RECORDS</h1>

<%= link_to "Add a New Record", new_record_path %>
<br>
<%= @records.each do |record| %>
  <%= link_to record.title, record_path(record) %>
  <%= link_to "EDIT", edit_record_path(record) %>
  <%= link_to "DELETE", record_path(record), method: :delete %>
  <br>
<% end %>
<br>
<%= link_to "Add a Movie", new_movie_path %>
<br>
<% @movies.each do |movie| %>
  <%= link_to movie.title, movie_path(movie) %>
  <%= link_to "EDIT", edit_movie_path(movie) %>
  <%= link_to "DELETE", movie_path(movie), method: :delete %>
  <br>
  <br>
<% end %>
</body>

</html>